FROM python:3.12.4-slim-bullseye

WORKDIR /app

COPY requirements.txt /app


RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

RUN groupadd -r ai-group && useradd -g ai-group ai-user && \
    chown -R ai-user:ai-group /app

USER ai-user

RUN chmod u+x start-huey.sh

EXPOSE 8000
CMD ["./start-huey.sh"]